### ISSUE TITLE
Run file_sync.py error

### ISSUE THREAD

**Issue by mikezhaoiot** [iWoz/file_sync#2]
Hi.

![qq 20161121210408](https://cloud.githubusercontent.com/assets/16273854/20483743/a4bf0b74-b02e-11e6-9725-f628526a25d3.png)

@iWoz

**Comment by iWoz** [comment]
@wisezhao Ops, It test well in my Mac...
It may be fixed now.

**Comment by mikezhaoiot** [comment]
In Windows7, How to modify the script!

**Comment by iWoz** [comment]
@wisezhao please pull the last commit and test.
