### ISSUE TITLE
can sync between two local computers without through github

### ISSUE THREAD

**Issue by kpeng2016** [iWoz/file_sync#4]
Hi,
Is that possible I can sync between two local computers without go through github.
I have a home server, that all files backup, how can I push the diff to home server from other computer?

**Comment by iWoz** [comment]
Git offers a way to log the file change and persistence. Github is a free and powerful site to offer this service. If you only want to sync between your local computers, you don't need Github, you can simply use the cloud sync tools like Dropbox.
